# Week 4 Project

## Becky Honnold

<!-- leave this material as is -->
Compiled on `r date()`.

```{r include = FALSE}
library(DataComputing)
library(mosaicData)
```
<!-- put your content after this line -->

Here is my content!

```{r}
DailyBirths <-
  Birthdays %>%
  group_by(date) %>%
  summarise(count = sum(births))

DailyBirths
```


```{r}
plot(DailyBirths)
```
```{r}
Birthdays %>%
  group_by(wday) %>%
  summarise(count = sum(births)) %>%
  arrange(count)
```

```{r}
Birthdays %>%
  mutate(Month = lubridate :: month(date)) %>%
  group_by(Month) %>%
  summarise(count = sum(births))
```
```{r}
Birthdays %>%
  mutate(JDAY = lubridate :: yday(date)) %>%
  group_by(JDAY) %>%
  summarise(count = sum(births))
```
```{r}
Birthdays %>%
  mutate(Week_day  = lubridate ::wday(date,label = T)) %>%
  group_by(Week_day) %>%
  summarise(count = n())


```

```{r}
MyTwoYears <-
  Birthdays %>%
  filter(year == 1980 | year == 1981)

MyTwoYears_N <-
  MyTwoYears %>%
  group_by(date) %>%
  summarise(count = sum(births)) %>%
  mutate(week_day = lubridate::wday(date,label = T)) 

MyTwoYears_N


ggplot(data=MyTwoYears_N,aes(x=date,y=count))+geom_point()+aes(colour=week_day)

ggplot(data=MyTwoYears_N,aes(x=date,y=count))+geom_line(aes(colour=week_day))
```
It looks as if there were many less births on the weekend in comparison to the week days. 


##Question 5
```{r}
holidays <- read.csv("http://tiny.cc/dcf/US-Holidays.csv") %>%
  mutate(date = as.POSIXct(lubridate::dmy(date))) %>%
  #mutate(date = as.numeric(date)) %>%
  filter(year == 1980 | year == 1981)

holidays
```

##Question 6
```{r}


ggplot(data=MyTwoYears_N,aes(x=date,y=count))+
  geom_line(aes(colour=week_day)) + 
  geom_vline(data = holidays, aes(xintercept = as.numeric(date)))+ 
  geom_text(data = holidays,aes(x = date,label = holiday), y = 9000, angle = 45)
```

##Question 7

```{r}
MyTwoYears_N2 <-
  MyTwoYears_N %>%
  mutate(is_holiday = as.numeric(date) %in% holidays$date)

MyTwoYears_N2

ggplot(data=MyTwoYears_N2,aes(x=date,y=count))+geom_point()+aes(colour=week_day) + facet_wrap(~is_holiday)

ggplot(data=MyTwoYears_N2,aes(x=date,y=count))+geom_point()+aes(colour=is_holiday) + facet_wrap(~week_day)
```


