# Week 7 Short Answer Questions

## Your name should appear here!

<!-- leave this material as is -->
Compiled on `r date()`.

```{r include = FALSE}
library(DataComputing)
```
<!-- put your content after this line -->

15.1

• "April 30, 1777" Johann Carl Friedrich Gauss 
• "06-23-1912" Alan Turing’s birthday 
• "3 March 1847" Alexander Graham Bell’s birthday 
• "11:00 am on Nov. 11th, 1918 at 11:00 am" Armistice ending World War I on the Western Front. 
• "July 20, 1969" First manned moon landing 

```{r}
lubridate::mdy("April 30, 1777")-lubridate::ymd("1992-12-21")
lubridate::mdy("06-23-1912")-lubridate::ymd("1992-12-21")
lubridate::dmy("3 March 1847")-lubridate::ymd("1992-12-21")
lubridate::mdy("Nov. 11th, 1918")-lubridate::ymd("1992-12-21")
lubridate::mdy("July 20, 1969")-lubridate::ymd("1992-12-21")
```


15.2

```{r}
tidyr::extract_numeric("42,659.30")
"Neither works for b."
tidyr::extract_numeric("Nineteen")
tidyr::extract_numeric("£100")
"Neither works for e."
tidyr::extract_numeric("9.8 m/sˆ2")
"Neither works for g."
"Neither works for h."
tidyr::extract_numeric( "42.659,30")
```


16.1

```{r}
BabyNames %>%
  filter(sex=="M",grepl("[(aeiou)]$",name)) %>%
  group_by(name) %>%
  summarise(total = sum(count)) %>%
  filter(rank(desc(total))<=10)

BabyNames %>%
  filter(grepl("joe|jo$",name)) %>%
  group_by(name) %>%
  summarise(total = sum(count)) %>%
  filter(rank(desc(total))<=10)

```


16.2

This would match to a phone number


16.3

2 characters

```{r}
7+3+2+2+2+1+4+2+1+10+8+3+3+1+2+2+1+3+4
```

Many of these are States, but not all of them

