# Week 6 Short Answer Questions

## Phuc Nguyen

<!-- leave this material as is -->
Compiled on `r date()`.

```{r include = FALSE}
library(DataComputing)
```
<!-- put your content after this line -->

##12.1
```{r}
BabyNames %>%
  filter(sex == "F") %>%
  group_by(name) %>%
  summarise(total = sum(count)) %>%
  arrange(desc(total)) %>%
  head(5)
  
BabyNames %>%
  filter(sex == "M") %>%
  group_by(name) %>%
  summarise(total = sum(count)) %>%
  arrange(desc(total)) %>%
  head(5)
```

##12.2
```{r}
GplyphReady <- BabyNames %>% 
  group_by(year) %>% #rank within each year
  mutate(rank = rank(desc(count))) %>% #in descending order
  mutate(frac_in_top_100 = ifelse(rank <= 100, TRUE, FALSE)) %>%
  group_by(year,frac_in_top_100) %>%
  summarise(total = sum(count)) %>%
  spread(key=frac_in_top_100, value=total) %>%
  mutate(frac = `TRUE`/(`TRUE`+`FALSE`))
```

```{r}
GplyphReady %>% ggplot(aes(x = year, y = frac)) + geom_smooth() + geom_point()
```

##12.3
a. transformation 
b. transformation
c. summary
d. transformation
e. transformation
f. summary
g. transformation
h. neither

##13.1
There are 8 vertices and 9 edges

##13.2
1.yes. A, B, C, D are vertices
2.Table 2
3.
Table 1: there's no edges between C and B
Table 3: D is in its own column

##13.3
Table 2

##13.4
1. exports
2. pop

##14.1
```{r}
mosaicData::CPS85 %>%
  ggplot(aes(x=sex, y=wage)) + geom_boxplot(aes(fill=sex))
```

##14.3
Around 1.6

##14.7
```{r}
mosaicData::CPS85 %>%
  ggplot(aes(educ, wage, colour = sex)) + geom_point() + geom_smooth(method = "lm")
```

##14.10
```{r}
ggplot(Galton, aes(height, fill = sex, alpha = 1/3)) + geom_density()
```
