# Week 3 Project

## Sam Erickson

<!-- leave this material as is -->
Compiled on `r date()`.

```{r, include=FALSE}
library(DataComputing)
library(mosaicData)
library(ggplot2)
```
<!-- put your content after this line -->

```{r}
ggplot(data=CPS85, aes(x=exper,y=wage)) +
  geom_point()+
  aes(colour=married)+
  facet_wrap(~sector,ncol=4)
```


```{r}
 ggplot( data = NCHS, aes(x = bmi)) +
  geom_density(adjust=0.4,alpha=0.3) +
  aes(colour=sex,fill=sex,) + 
  facet_wrap(~pregnant, ncol=4) + labs(title="") + 
  theme(legend.position="right") 
```

1. Which color diamonds seem to be largest on average?

```{r}
names(diamonds)
diamonds %>%
  group_by(color) %>%
  summarize(averageSize = mean(carat)) %>%
  arrange(desc(averageSize)) %>%
  head(1)
```
Color J (worst color) appears to be largest.

2. Which clarity of diamonds has the largest average "table" per carat?

```{r}
diamonds %>%
  group_by(clarity) %>%
  summarize(tablePerCarat = mean(table)/mean(carat)) %>%
  arrange(desc(tablePerCarat)) %>%
  head(1)

```

VVS1 clarity has an average table per carat of 113.

```{r}
nrow(Minneapolis2013)
names(Minneapolis2013)
```
```{r}
Minneapolis2013 %>%
  group_by(Second) %>%
  summarize(total = count(Second)) %>%
  arrange(desc(total)) %>%
  head(5)

Minneapolis2013 %>%
  filter(First=='undervote') %>%
  summarize(FirstUndervotes = count(First))

Minneapolis2013 %>%
  filter(Second=='undervote') %>%
  summarize(SecondUndervotes = count(Second))

Minneapolis2013 %>%
  filter(Third=='undervote') %>%
  summarize(ThirdUndervotes = count(Third))

Minneapolis2013 %>%
  group_by(Second) %>%
  filter(First=='BETSY HODGES') %>%
  summarize(count = count(Second)) %>%
  arrange(desc(count)) %>%
  head(3)

  
```

```{r}
Minneapolis2013 %>%
  group_by(Precinct) %>%
  summarize(TotalVotes = count(Precinct),underVoteTotal=count(First == 'undervote'),fraction=underVoteTotal/TotalVotes) %>%
  arrange(desc(fraction)) %>%
  head(3)
```


```{r}
Minneapolis2013 %>%
  group_by(Precinct) %>%
  summarize(TotalVotes = tally(Precinct),underVoteTotal=count(First == 'undervote'),fraction=underVoteTotal/TotalVotes) %>%
  arrange(desc(fraction)) %>%
  head(3)
```




